services:
    rmcgirr83.posteripinviewtopic.listener:
        class: rmcgirr83\posteripinviewtopic\event\listener
        arguments:
            - '@auth'
            - '@controller.helper'
            - '@language'
            - '@template'
            - '@rmcgirr83.posteripinviewtopic.core.freegeoip'
        tags:
            - { name: event.listener }

    rmcgirr83.posteripinviewtopic.core.freegeoip:
        class: rmcgirr83\posteripinviewtopic\core\freegeoip
        arguments:
            - '@auth'
            - '@language'
            - '@request'
